; GORILLA.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Gorilla
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 32 x 32
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Gorilla", ROM0

; Start of tile array.
Gorilla::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$01,$01,$03,$03
DB $07,$07,$0F,$0F,$1F,$1F,$1F,$1F
DB $00,$00,$00,$00,$01,$01,$03,$03
DB $07,$07,$0E,$0F,$0E,$0F,$1E,$1F
DB $3F,$3F,$7F,$7F,$FF,$FF,$3F,$FF
DB $0F,$FF,$0F,$FF,$07,$FF,$0F,$FF
DB $1F,$1F,$1F,$1F,$1F,$1F,$1F,$1F
DB $1F,$1F,$1F,$1F,$1F,$1F,$1E,$1F
DB $1E,$1E,$1E,$1E,$0E,$0E,$0F,$0F
DB $0F,$0F,$08,$0F,$08,$0F,$1F,$1F
DB $0F,$FF,$0F,$FF,$0F,$FF,$0F,$FF
DB $0F,$FF,$0F,$FF,$07,$FF,$07,$FF
DB $07,$07,$07,$07,$7F,$7F,$FF,$FF
DB $00,$00,$C0,$C0,$60,$E0,$E0,$E0
DB $78,$78,$FC,$FC,$FE,$FE,$FF,$FF
DB $F0,$FF,$7F,$FF,$71,$79,$70,$FF
DB $F0,$FF,$F8,$FF,$F8,$FF,$FC,$FF
DB $FC,$FF,$FE,$FF,$FF,$FF,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $80,$80,$80,$80,$00,$00,$80,$80
DB $40,$C0,$40,$C0,$20,$E0,$E0,$E0
DB $20,$E0,$E0,$E0,$C0,$C0,$80,$80
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FE,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FE,$FF,$FF,$FF,$FF,$FF
DB $1F,$1F,$08,$0F,$08,$0F,$0F,$0F
DB $C0,$C0,$C0,$C0,$C0,$C0,$60,$E0
DB $60,$E0,$30,$F0,$10,$F0,$10,$F0
DB $98,$F8,$88,$88,$88,$88,$D8,$D8
DB $70,$70,$C0,$C0,$60,$E0,$E0,$E0

; End of GORILLA.Z80
