; GORILLA.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Gorilla
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 32 x 32
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Gorilla", ROM0

; Start of tile array.
Gorilla::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$01,$01,$03,$03
DB $05,$07,$09,$0F,$13,$1F,$13,$1F
DB $00,$00,$00,$00,$01,$01,$02,$03
DB $04,$07,$09,$0F,$09,$0F,$11,$1F
DB $20,$3F,$40,$7F,$E0,$FF,$30,$FF
DB $08,$FF,$0C,$FF,$04,$FF,$0C,$FF
DB $13,$1F,$13,$1F,$11,$1F,$11,$1F
DB $11,$1F,$11,$1F,$13,$1F,$12,$1F
DB $12,$1E,$1E,$1E,$0E,$0E,$0F,$0F
DB $0F,$0F,$08,$0F,$08,$0F,$1F,$1F
DB $0C,$FF,$0C,$FF,$0C,$FF,$0C,$FF
DB $0C,$FF,$0C,$FF,$04,$FF,$04,$FF
DB $04,$07,$07,$07,$7F,$7F,$FF,$FF
DB $00,$00,$C0,$C0,$60,$E0,$E0,$E0
DB $78,$78,$84,$FC,$02,$FE,$1F,$FF
DB $30,$F0,$BF,$FF,$17,$71,$90,$F0
DB $10,$F3,$18,$F9,$08,$F8,$0F,$FF
DB $06,$FE,$02,$FE,$01,$FF,$01,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $80,$80,$80,$80,$00,$00,$80,$80
DB $40,$40,$40,$40,$20,$20,$E0,$E0
DB $20,$20,$E0,$E0,$C0,$C0,$80,$80
DB $01,$FF,$01,$FF,$01,$FF,$03,$FF
DB $02,$FF,$03,$FF,$03,$FF,$03,$FF
DB $01,$FF,$FE,$FF,$FF,$FF,$FF,$FF
DB $1F,$1F,$08,$0F,$08,$0F,$0F,$0F
DB $C0,$C0,$C0,$C0,$C0,$C0,$60,$E0
DB $60,$E0,$30,$F0,$10,$F0,$10,$F0
DB $98,$F8,$88,$88,$88,$88,$D8,$D8
DB $70,$70,$C0,$C0,$60,$E0,$E0,$E0

; End of GORILLA.Z80
