; MAP1TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : map1Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "map1Tiles", ROM0

; Start of tile array.

map1Tiles::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $20,$FF,$60,$FF,$48,$FF,$78,$FF
DB $08,$FF,$38,$FF,$20,$FF,$20,$FF
DB $04,$FF,$06,$FF,$12,$FF,$1E,$FF
DB $10,$FF,$1C,$FF,$04,$FF,$04,$FF
DB $00,$FF,$0E,$FF,$EB,$FF,$28,$FF
DB $3C,$FF,$00,$FF,$00,$FF,$00,$FF
DB $20,$00,$B6,$00,$FF,$00,$FF,$00
DB $FF,$FF,$18,$FF,$00,$FF,$00,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $10,$10,$14,$14,$18,$18,$10,$10
DB $10,$10,$50,$50,$30,$30,$10,$10
DB $10,$10,$50,$50,$30,$30,$10,$10
DB $10,$10,$14,$14,$18,$18,$10,$10


; End of MAP1TILES.Z80
