; MAP1TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : map1Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "map1Tiles", ROM0

; Start of tile array.

map1Tiles::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $20,$FF,$60,$FF,$48,$FF,$78,$FF
DB $08,$FF,$38,$FF,$20,$FF,$20,$FF
DB $04,$FF,$06,$FF,$12,$FF,$1E,$FF
DB $10,$FF,$1C,$FF,$04,$FF,$04,$FF
DB $00,$FF,$0E,$FF,$EB,$FF,$28,$FF
DB $3C,$FF,$00,$FF,$00,$FF,$00,$FF
DB $20,$00,$B6,$00,$FF,$00,$FF,$00
DB $FF,$FF,$18,$FF,$00,$FF,$00,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$0C,$00,$0C,$00,$1C,$00,$38
DB $00,$30,$00,$30,$00,$38,$00,$18
DB $00,$18,$00,$18,$00,$1C,$00,$0E
DB $00,$06,$00,$06,$00,$0E,$00,$0C


Verja::
DB $49,$49,$49,$49,$FF,$FF,$49,$49
DB $49,$49,$FF,$E3,$7F,$41,$6B,$55
DB $FF,$C1,$55,$49,$5D,$41,$FF,$FF
DB $49,$49,$49,$49,$FF,$FF,$49,$49


; End of MAP1TILES.Z80
