; MAP1TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : map1Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "map1Tiles", ROM0

; Start of tile array.

map1Tiles::
DB $20,$FE,$60,$FE,$48,$FE,$78,$FE
DB $08,$FE,$38,$FE,$20,$FE,$20,$FE
DB $04,$7F,$06,$7F,$12,$7F,$1E,$7F
DB $10,$7F,$1C,$7F,$04,$7F,$04,$7F
DB $00,$FF,$0E,$FF,$EB,$FF,$28,$FF
DB $3C,$FF,$00,$FF,$00,$FF,$00,$00
DB $20,$00,$B6,$00,$FF,$00,$FF,$00
DB $FF,$FF,$18,$FF,$00,$FF,$00,$FF

; End of MAP1TILES.Z80
