; player.asm
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 16
;   Tiles                : 0 to 6
;
;   Palette colors       : %11 10 00 01
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", ROM0

; Start of tile array.
Player_back_l::
DB $03,$03,$03,$02,$03,$05,$01,$07
DB $00,$03,$00,$01,$03,$00,$00,$07
DB $00,$07,$00,$07,$00,$07,$03,$04
DB $00,$03,$01,$02,$00,$02,$00,$02

Player_back_r::
DB $C0,$C0,$C0,$40,$C0,$A0,$80,$E0
DB $00,$C0,$00,$80,$C0,$00,$00,$E0
DB $00,$E0,$00,$E4,$08,$E8,$D0,$30
DB $20,$E0,$80,$40,$00,$40,$00,$40

Player_stand::
DB $00,$00,$3E,$3E,$F8,$BE,$F2,$BE
DB $A0,$BF,$81,$BF,$80,$9C,$2C,$13
DB $00,$3C,$00,$3C,$00,$3C,$2C,$10
DB $18,$24,$18,$24,$00,$24,$00,$36

Player_walk::
DB $3E,$3E,$F8,$BE,$F2,$BE,$A0,$BF
DB $80,$BE,$81,$9D,$2C,$10,$00,$3F
DB $00,$3C,$00,$3C,$2C,$10,$18,$24
DB $18,$26,$00,$63,$00,$40,$00,$00

Player_blowgun::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$B0,$F8,$00,$40,$00,$80
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00

Player_bullet::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$3C,$38,$00,$00,$00,$00

Player_life::
DB $00,$00,$1C,$00,$7E,$1C,$DA,$5C
DB $F1,$5E,$E2,$5C,$5C,$00,$00,$00

; End of PLAYER.asm